export { default as TermsAndConditions } from "./TermsAndConditions/TermsAndConditions";
export { default as AboutUs } from "./AboutUs/AboutUs";
export { default as PrivacyPolicy } from "./PrivacyPolicy/PrivacyPolicy";
export { default as Home } from "./Home/Home";
export { default as Shop } from "./Shop/Shop";
export { default as MyAccount } from "./MyAccount/MyAccount";
export { default as ProductDetails } from "./ProductDetails/ProductDetails";
export { default as LoginPage } from "./LoginPage/LoginPage";
export { default as RegisterPage } from "./RegisterPage/RegisterPage";
